### ISSUE TITLE
[BUG] Rare RAR file with special characters

### ISSUE THREAD

**Issue by aonez** [aonez/Keka#713]
Reported via MAS review and mail by Holger.

- The `test-KO.rar` file was provided by Holger and fails to extract with every method I've tried. It also shows incorrect symbols in Windows XP-10 using latest WinRAR.
- The file `test-OK.rar` contains the same filenames but extracts properly anywhere.

Test files: [Test.zip](https://github.com/aonez/Keka/files/5647553/Test.zip)

**Comment by VaslD** [comment]
They do not contain the same file names.

*KO.rar* has these files:

```
Auto-detected archive type: Rar
Entry: Fratello Sole Sorella Luna (Dolce ￾ Sentire).txt (F)
Entry: Huh die Jl￾ser, huh die Tasse.txt (F)
Entry: Intermezzo from L'arl￾sienne Suite.txt (F)
```

(Visually)

<img width="600" alt="Screen Shot 2020-12-15 at 11 23 36" src="https://user-images.githubusercontent.com/3415065/102166836-0567c480-3ec8-11eb-9bc9-0b756080b51e.png">

While *OK.rar* has:

```
Auto-detected archive type: Rar
Entry: Fratello Sole Sorella Luna (Dolce è Sentire).txt (F)
Entry: Huh die Jläser, huh die Tasse.txt (F)
Entry: Intermezzo from L'arlésienne Suite.txt (F)
```

Although you can somewhat construct Unicode characters that look the same in different ways (from different sequences), this is not the case. File names in *KO.rar* can't even render in my web browser.

On .NET Core (which I assume wraps each platform's native filesystem APIs), attempting to access file with such characters in its name throws exception:

```
System.IO.IOException: Illegal byte sequence
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.FileInfo.Create()
   at Unzip.Program.Main(String[] args)
```

**Comment by VaslD** [comment]
The culprit seems to be character `U+FFFE` in the file name, which is not a valid Unicode character according to standards I could find online.

Other unrenderable characters work fine as file names. I can successfully create empty files, just that their names appear as [?] in Finder.

**Comment by aonez** [comment]
Thanks for all the testing and descriptions @VaslD. I'm not sure I can fix this issue.

**Comment by VaslD** [comment]
Don't think this needs fixing.

An archive with `U+FFFE` present is either maliciously crafted (like a zip-bomb), authored with software that doesn't conform to standards, or simply corrupted. Either way there's nothing you can do.

I guess you *can* try to filter out invalid characters during extraction but that's asking too much from an archiver app.
